### ISSUE TITLE
Create mockup navbar and footer

### ISSUE THREAD

**Issue by jimanaka** [textbook-hunt/textbookhunt#10]
Do all work for this task in a branch called "issue-10"

Navbar menu (note: links do not need to function properly for the mockup):
- To home link at top left with the text "Textbook Hunt"
- To profile link.  Links to a user's profile page.  If you are not logged in, should link to the signup/ signin page
- To listings link.  Should link to the "listings" page
- To post listing link.  Should link to the "post listing" form page

Footer
- Padding separating the main page content from the bottom margin

**Comment by Ray4898** [comment]
finished
