### ISSUE TITLE
Create mockup signup page

### ISSUE THREAD

**Issue by jimanaka** [textbook-hunt/textbookhunt#3]
Do all work for this task in a branch called issue-03.

Tasks:
- User text fields for email and password
- After pressing the register button, show a sweet alert if successful or not,
- Data should be stored in the database when they register.

**Comment by Ray4898** [comment]
A sign up page where the user can create an account. It would contain a sign up form. User need to create their username, password and provide the UH email.  Then the user can click on the sign up bottom, and the system would add the user information to the database.

**Comment by Ray4898** [comment]
done
